### ISSUE TITLE
I need some help adding this to my code

### ISSUE THREAD

**Issue by waleed-alharthi** [remihenache/ThreadSafeDbContext#1]
first of all, THANK YOU! this is long overdue with all the headache from a random rare parallel lazy load which crashes my whole app.

my challenge is with using the NuGet package. I'll try copying your classes directly to see if it works.

below is the issue I'm having when using the NuGet package. Additionally I can't inherit "ThreadSafeDbContext" because it's a namespace so i got the whole "ThreadSafeDbContext.ThreadSafeDbContext" thing going on.

![image](https://github.com/remihenache/ThreadSafeDbContext/assets/71645462/af63956c-fd1f-44b8-ac1c-ee0d1352f67c)

![image](https://github.com/remihenache/ThreadSafeDbContext/assets/71645462/9fa7b105-4184-479b-a99d-95d153bc8e6c)

**Comment by remihenache** [comment]
Oh effectivelly, I missed it.
You can workaround by injecting a DbContextOptions<ThreadSafeDbContext> instead of DbContextOptions<MyDbContext>
I'll update this soon to make it work as it does

**Comment by waleed-alharthi** [comment]
you mean "DbContextOptionsBuilder"?

I got this to work:
![image](https://github.com/remihenache/ThreadSafeDbContext/assets/71645462/ed530c38-1e7e-4a63-a9ef-6bf7e0fbf500)

**Comment by remihenache** [comment]
I updated the source, and the package, I changed the namespace to avoid naming conflict.
I also changed the DbContextOptionsBuilder, to allow you to use your own type in the generic definition.
Do no hesitate to update your package reference.
And do no hesitate to tell me if you got some problems.

**Comment by waleed-alharthi** [comment]
I'll give it a try now and confirm. thanks!

**Comment by waleed-alharthi** [comment]
inheritance now is straightforward. the issue left is using options without a builder:
using builder compiled fine but gave me issues when the services were getting warmed up.

![image](https://github.com/remihenache/ThreadSafeDbContext/assets/71645462/670762d8-0cac-4e9c-a8f8-cc955f61a382)

```
Severity	Code	Description	Project	File	Line	Suppression State

Error	CS1503	Argument 1: cannot convert from 

'Microsoft.EntityFrameworkCore.DbContextOptions<Clamp.Data.AppDbContext>' to 

'Microsoft.EntityFrameworkCore.DbContextOptionsBuilder'
```

**Comment by remihenache** [comment]
Yes, I can't use directly the Options, because I had to inject something into it, so I use the builder.
You can also use the parameterless constructor and override the OnConfiguring if you prefer.
I'll try to find a way to enable the Option signature instead of the OptionsBuilder, but for now, I don't see how.

**Comment by waleed-alharthi** [comment]
I'll massage my code around this to get it to work. Many thanks for your help!

**Comment by remihenache** [comment]
In case you're still interested, I was able to adapt the OptionsBuilder constructor to Options, to be fully consistent with the DbContext
So, since version 1.0.7, the OptionsBuilder constructor gives way to the one taking Options directly

**Comment by waleed-alharthi** [comment]
Updated my project. I confirm it works well using options!
