### ISSUE TITLE
The connection is already open

### ISSUE THREAD

**Issue by khoinguyen-hm** [remihenache/ThreadSafeDbContext#4]
I use ThreadSafeContext to run this task
 await Task.WhenAll(costcodeTask, poheaderTask, apCheckHistoryTask);
But get error The connection is already open

**Comment by remihenache** [comment]
Hi,
Can you provide me some more information, like the EntityFramework query you try to execute? And how your DbContext is declared/used ?
That'll be helpfull for me
Can you also tell me if you are using the preview version or the normal version ?
